send options ping
jambonz/sbc-sip-sidecar pull request #48
Opened 2023-12-12 12:15 UTC by xquanluu

2023-12-12 13:56 UTC, davehorton requested changes
I think we need to revise this.  Unlike outbound REGISTERs, where we only send from one SBC, we should send OPTIONS ping from all SBCs.  Thus the functionality should be factored out of sip-trunk-register.js into its own file.

2023-12-12 14:18 UTC, xquanluu commented
Fixed

2023-12-12 14:22 UTC, davehorton requested changes

2023-12-12 14:22 UTC, davehorton commented on lib/sip-trunk-options-ping.js
> +      const gws = await lookupSipGatewaysByFilters({send_options_ping: true, outbound: true, is_active: true});
is_active: true means that once we mark a gateway as inactive/down we will never test it again..hmmm

2023-12-12 14:22 UTC, davehorton commented on lib/sip-trunk-options-ping.js
> +      const gws = await lookupSipGatewaysByFilters({send_options_ping: true, outbound: true, is_active: true});
any ideas on this?  Do we in fact need a new property in the sip_gateways table?  Or should we keep track of all active/down gateways in redis?

2023-12-12 14:24 UTC, davehorton commented on lib/sip-trunk-options-ping.js
> +      const gws = await lookupSipGatewaysByFilters({send_options_ping: true, outbound: true, is_active: true});
I guess we really have two different pieces of information we are tracking:
- active/inactive -- do we want to use this gateway at all
- up/down -- for active gateways, is it responding to options pings

I kind of like not changing the mysql schema and instead keeping a list in redis of all active/down gateways

2024-03-08 15:14 UTC, davehorton commented
@xquanluu we're almost ready to merge this, as the first feature of 0.8.6.  Can you rebase

2024-03-30 09:36 UTC, xquanluu commented on lib/sip-trunk-options-ping.js
> +      const gws = await lookupSipGatewaysByFilters({send_options_ping: true, outbound: true, is_active: true});
Fixed

2024-03-30 13:18 UTC, davehorton approved these changes

2024-03-30 13:18 UTC, merged